//! Byte-identity pin for the binary-COPY VALUE encoding.
//!
//! Postgres binary COPY carries no per-field type tag: the server trusts the
//! column list and reads the declared width. A value encoded one byte
//! differently is therefore either a loud format error or — for same-width
//! types — a SILENTLY different value landing in the table. Round-trip tests
//! against a live server catch the first and can miss the second, so the
//! encoder's output is pinned as literal bytes here.
//!
//! Scope is values only. The tuple framing (field count, per-field length
//! prefix, trailer) lives inside the driver's copy writer, whose only
//! constructor needs a live `CopyInSink`; framing is proven by the live
//! destination-conformance suite instead.
//!
//! Regenerate deliberately, never reflexively — a diff here means the bytes
//! Postgres receives changed:
//!
//! ```text
//! RDLT_REPIN=1 cargo nextest run -p rdlt-connector-postgres copy_wire_pin
//! ```

use std::fmt::Write as _;
use std::path::PathBuf;

use rdlt_connector_postgres::testsupport::destination::encode_pin_values;

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/copy_values.hex")
}

/// Render the encoder's output as a diffable text table: one line per
/// (column, row), NULL spelled out so a null/empty confusion cannot hide.
fn render() -> String {
    let mut rendered = String::new();
    rendered.push_str("# Postgres binary-COPY value bytes, per column per row.\n");
    rendered.push_str(
        "# Generated by tests/cases/test_copy_wire_pin.rs — see that file before editing.\n",
    );
    for (column, cells) in encode_pin_values() {
        for (row, cell) in cells.iter().enumerate() {
            let cell_text = match cell {
                None => "NULL".to_string(),
                Some(bytes) => {
                    let mut hex = String::with_capacity(bytes.len() * 2);
                    for byte in bytes {
                        write!(hex, "{byte:02x}").expect("write to String");
                    }
                    hex
                }
            };
            writeln!(rendered, "{column}[{row}] = {cell_text}").expect("write to String");
        }
    }
    rendered
}

#[test]
fn copy_value_bytes_match_the_pin() {
    let path = fixture_path();
    let actual = render();

    if std::env::var_os("RDLT_REPIN").is_some() {
        std::fs::create_dir_all(path.parent().expect("fixtures dir")).expect("create fixtures dir");
        std::fs::write(&path, &actual).expect("write pin");
        return;
    }

    let expected = std::fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "missing binary-COPY value pin at {}: {error}\n\
             regenerate with RDLT_REPIN=1 (and review the diff — these are the \
             bytes Postgres receives)",
            path.display()
        )
    });

    if actual != expected {
        let first_diff = expected
            .lines()
            .zip(actual.lines())
            .find(|(pinned, now)| pinned != now)
            .map(|(pinned, now)| format!("\n  pinned: {pinned}\n  now:    {now}"))
            .unwrap_or_else(|| "\n  (line count differs)".to_string());
        panic!(
            "binary-COPY value encoding changed — the bytes Postgres receives are \
             not what was pinned:{first_diff}\n\
             if the change is intended, re-pin with RDLT_REPIN=1 and justify it in \
             the change description"
        );
    }
}

/// The pin is only meaningful if it exercises every wire kind: a rewrite that
/// silently drops a variant would otherwise pass against a stale fixture.
#[test]
fn the_pin_covers_every_wire_kind() {
    let columns: Vec<String> = encode_pin_values()
        .into_iter()
        .map(|(name, _)| name)
        .collect();
    // One column per wire variant, all twelve.
    let expected = [
        "c_bool",
        "c_int8",
        "c_float8",
        "c_text",
        "c_bytea",
        "c_timestamptz",
        "c_timestamp",
        "c_date",
        "c_time",
        "c_numeric",
        "c_jsonb",
        "c_uuid",
    ];
    assert_eq!(columns, expected, "wire-kind coverage changed");
}

/// Every column carries a NULL and at least two non-null values, so the pin
/// binds the null path as well as the value path.
#[test]
fn every_pinned_column_has_a_null_and_two_values() {
    for (column, cells) in encode_pin_values() {
        let nulls = cells.iter().filter(|cell| cell.is_none()).count();
        let values = cells.iter().filter(|cell| cell.is_some()).count();
        assert_eq!(nulls, 1, "column `{column}` must pin exactly one NULL");
        assert_eq!(values, 2, "column `{column}` must pin two non-null values");
    }
}
